### ISSUE TITLE
_apollocaffe.so: undefined symbol: _ZN5caffe6TensorIfE7MulFromERKS1_

### ISSUE THREAD

**Issue by PierreHao** [Russell91/apollocaffe#10]
Hi, when i compile apollocaffe, all run successfully, but when i use python wrapper, import apollocaffe
, there is an error: apollocaffe/cpp/_apollocaffe.so: undefined symbol: _ZN5caffe6TensorIfE7MulFromERKS1_
this means the shared lib _apollocaffe.so is failed, my Makefile.config is from my caffe project, it works well. Does any one know what's the problem?
Thank you apollocaffe, it a great work.

**Comment by nicodjimenez** [comment]
There might be something wrong with the shared library libcaffe.so, this library should contain the symbols for the Tensor class methods.  Or maybe this library isn't getting loaded at runtime.  In my ~/.bashrc I have the following:
```
export APOLLO_ROOT="/Users/njimenez/apollocaffe"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$APOLLO_ROOT/build/lib # contains libcaffe.so
```

**Comment by Russell91** [comment]
Yea, can you confirm that you are not loading the wrong libcaffe.so? The fact that you can compile successfully, but you cannot run, is an indication that your LD_LIBRARY_PATH is linking to a bad libcaffe.so

**Comment by PierreHao** [comment]
Thank you. There is an other libcaffe.so, because i have the original caffe path in my environment path. After delete it, apollocaffe runs well

**Comment by oolongtea** [comment]
I got a related shared object file error:

```
>>> import apollocaffe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/developer/Miscellaneous/apollocaffe/python/apollocaffe/__init__.py", line 1, in <module>
    from cpp._apollocaffe import Tensor, ApolloNet, CppConfig, make_numpy_data_param, Blob
  File "/home/developer/Miscellaneous/apollocaffe/python/apollocaffe/cpp/__init__.py", line 1, in <module>
    import _apollocaffe
ImportError: libcaffe.so: cannot open shared object file: No such file or directory
```

After checking my environment variables, turns out I had set my `PYTHONPATH` correctly but did not set `LD_LIBRARY_PATH` to point to `apollocaffe/build`. Once these two variables were set, import worked fine.
