### ISSUE TITLE
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to `TIFFReadRGBAStrip@LIBTIFF_4.0' collect2: error: ld returned 1 exit status make: *** [.build_release/examples/cifar10/convert_cifar_data.bin] Error 1

### ISSUE THREAD

**Issue by mgarbade** [Russell91/apollocaffe#11]
I get this error during `make`. However I have opencv installed and the library is also located under that exact location.
Also I'm able to install other versions of caffe normally.
I'm using anacondapython. Maybe that is a problem for apollocaffe?

**Comment by Russell91** [comment]
This indicates that your opencv version may not be correct. I use Apollocaffe with Anaconda, so that alone is not the issue. Also, the error location is in caffe code that we haven't messed with.

I would recommend uninstalling opencv with conda and reinstalling it as a system dependency though.

**Comment by mgarbade** [comment]
I still get an error while trying to compile apollocaffe. In the meantime I switched back to the default opencv version of Ubuntu 14.04 (opencv 2.4.8) and to the default python.
This is my new error:  

    CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
    makecython++ python/apollocaffe/cpp/_apollocaffe.pyx '' "-MMD -MP -pthread -fPIC -DNDEBUG -    O2 -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/usr/local/cuda/include -Wall -Wno-sign-compare -L/usr/lib -L/usr/local/lib -L/usr/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -L.build_release/lib  -lcudart -lcublas -lcurand -lglog -lgflags -lprotobuf -lleveldb -lsnappy -llmdb -lboost_system -lhdf5_hl -lhdf5 -lm -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lstdc++ -lcblas -latlas -lboost_python -lpython2.7 -lcaffe" && rm python/apollocaffe/cpp/_apollocaffe.h
    /bin/sh: 1: makecython++: not found
    make: *** [apollo] Error 127

It is really strange because I definitely can compile caffe, even both with or without anaconda.

**Comment by mgarbade** [comment]
Ah, wait. Apparantly there was an error while trying to install the python requirements... to be continued

**Comment by mgarbade** [comment]
No chance. There is no luck:
    
    CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
    makecython++ python/apollocaffe/cpp/_apollocaffe.pyx '' "-MMD -MP -pthread -fPIC -DNDEBUG -O2 -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/usr/local/cuda/include -Wall -Wno-sign-compare -L/usr/lib -L/usr/local/lib -L/usr/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -L.build_release/lib  -lcudart -lcublas -lcurand -lglog -lgflags -lprotobuf -lleveldb -lsnappy -llmdb -lboost_system -lhdf5_hl -lhdf5 -lm -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lstdc++ -lcblas -latlas -lboost_python -lpython2.7 -lcaffe" && rm python/apollocaffe/cpp/_apollocaffe.h
    In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1761:0,
                     from /usr/include/python2.7/numpy/ndarrayobject.h:17,
                     from /usr/include/python2.7/numpy/arrayobject.h:4,
                     from python/apollocaffe/cpp/_apollocaffe.cpp:251:
    /usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated     NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^

I give it up for now and continue working with the normal caffe. Really sad... Thanks though

**Comment by Russell91** [comment]
Yes,  the most recent caffe is quite particular about the opencv version. But your last post shows a successful compilation.

**Comment by mgarbade** [comment]
So what version of OpenCV should I use for apollocaffe then?
For normal caffe I'm using the 2.4.8 which is standard under Ubuntu 14.04

Btw: I don't think my compilation was successful. This error appears when I call `make test`

    /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference     to `TIFFReadRGBAStrip@LIBTIFF_4.0'
    collect2: error: ld returned 1 exit status
    make: *** [.build_release/test/test_internal_thread.testbin] Error 1

**Comment by Russell91** [comment]
`make test` is not necessary to run any of the examples. If you can verify that you are able to compile and test the latest version of caffe, but not apollocaffe, I'd be very interested in gchatting about this specific problem.

**Comment by mgarbade** [comment]
I was finally able to compile apollocaffe and run the example. Sorry for bothering you with that.
I ended up using the system version of python instead of anaconda and as OpenCV I also took the standard apt-get version (2.4.8).
I don't know what was wrong with anaconda, I tried different versions (2.0.1 and 2.3.0). 

Still thanks with your patience. Maybe one day I try it again with anaconda...

**Comment by oolongtea** [comment]
For future users, I also came across make similar errors/warnings:

```
makecython++ python/apollocaffe/cpp/_apollocaffe.pyx '' "-MMD -MP -pthread -fPIC -DNDEBUG -O2 -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/usr/local/cuda/inc
lude -Wall -Wno-sign-compare -L/usr/lib -L/usr/local/lib -L/usr/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -L.build_release/lib  -lcudart -lcublas -lcurand -lglog -lgflags -lprotobuf -lleveldb -lsnappy -llmdb -lboost_system -lhdf5_hl -lhdf5 -lm -lop
encv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lstdc++ -lcblas -latlas -lboost_python -lpython2.7 -lcaffe" && rm python/apollocaffe/cpp/_apollocaffe.h
/bin/sh: 1: makecython++: not found
make: *** [apollo] Error 127
```
The solution was: `pip install runcython`

Next, I got the following warning (compilation was successful though):

```
$ make                                                                                                                                                                                                  
makecython++ python/apollocaffe/cpp/_apollocaffe.pyx '' "-MMD -MP -pthread -fPIC -DNDEBUG -O2 -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/usr/local/cuda/inc
lude -Wall -Wno-sign-compare -L/usr/lib -L/usr/local/lib -L/usr/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -L.build_release/lib  -lcudart -lcublas -lcurand -lglog -lgflags -lprotobuf -lleveldb -lsnappy -llmdb -lboost_system -lhdf5_hl -lhdf5 -lm -lop
encv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lstdc++ -lcblas -latlas -lboost_python -lpython2.7 -lcaffe" && rm python/apollocaffe/cpp/_apollocaffe.h
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1761:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:17,
                 from /usr/include/python2.7/numpy/arrayobject.h:4,
                 from python/apollocaffe/cpp/_apollocaffe.cpp:250:
/usr/include/python2.7/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
```

After that, `make test` successfully finished.

**Comment by Russell91** [comment]
If anyone knows how to get rid of the numpy warning for new users (without them having to edit the file), comments would be appreciated.

**Comment by oolongtea** [comment]
At the bottom of the Makefile, adding the flag `-Wno-cpp` will silence the numpy warning:

```
makecython++ python/apollocaffe/cpp/_apollocaffe.pyx '' "$(CXXFLAGS) -Wno-cpp $(PYTHON_LDFLAGS) -lcaffe" && rm python/apollocaffe/cpp/_apollocaffe.h
```

Idea was taken from [this topographica GitHub discussion](https://github.com/ioam/topographica/issues/559). Further discussion at [numpy issue 3008](https://github.com/numpy/numpy/issues/3008) and [cython documentation that mentions that we can ignore the warning](http://docs.cython.org/src/reference/compilation.html#configuring-the-c-build).

**Comment by Russell91** [comment]
Awesome - just fixed this: https://github.com/Russell91/apollocaffe/commit/68417ce0af346f31e3c35e9d78f6074ecb849209

**Comment by Russell91** [comment]
@mgarbade Just ran into a similar problem with a new anaconda distribution. Caffe has a similar issue opened up; see https://github.com/BVLC/caffe/issues/1599.

**Comment by HackToHell** [comment]
`conda remove libtiff` was the only thing that worked for me. +1

**Comment by kyuusaku** [comment]
I reinstalled the anaconda (2.3.0). It worked for me. 

fixed the error /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libopencv_highgui.so: undefined reference to `TIFFReadRGBAStrip@LIBTIFF_4.0' collect2: error: ld returned 1 exit status make: ***

I found that one cannot simply copy an installed anaconda package from another computer, even though it will be used in the same environment.

**Comment by hongzhenwang** [comment]
when meet the error " undefined reference to `png_create_read_struct@PNG16_0'" (using anaconda)

you can fix this by by adding an -rpath in  Makefile.config :

LINKFLAGS := -Wl,-rpath,$(HOME)/anaconda/lib

then you will meet the error "makecython++: not found", can fix it by 
  pip install runcython 
@mgarbade

**Comment by wanghm92** [comment]
I have the same issue with running "makecython++". @oolongtea was saying:
`The solution was: pip install runcython`

However, it tries install `runcython` during the `make`, and the requirements are already satisfied. Below is the part of log with the error:
`CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp`
`pip install runcython`
`Requirement already satisfied (use --upgrade to upgrade): runcython in /home/wanghm/.local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): Cython>=0.10 in /home/wanghm/.local/lib/python2.7/site-packages (from runcython)`
`Cleaning up...`
`makecython++ python/apollocaffe/cpp/_apollocaffe.pyx '' "-MMD -MP -pthread -fPIC -DNDEBUG -O2 -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I/usr/local/cudnn-4.0/cuda/include -I.build_release/src -I./src -I./include -I/usr/local/cuda/include -Wall -Wno-sign-compare -Wno-cpp -L/usr/lib -L/usr/local/lib -L/usr/lib -L/usr/local/cudnn-4.0/cuda/lib64 -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -L.build_release/lib  -lcudart -lcublas -lcurand -lglog -lgflags -lprotobuf -lleveldb -lsnappy -llmdb -lboost_system -lhdf5_hl -lhdf5 -lm -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lstdc++ -lcblas -latlas -lboost_python -lpython2.7 -lcaffe" && rm python/apollocaffe/cpp/_apollocaffe.h
/bin/sh: 1: makecython++: not found
make: *** [apollo] Error 127`

I tried intall runcython myself with "pip install runcython --user", which shows the same lines:

`Requirement already satisfied (use --upgrade to upgrade): runcython in /home/wanghm/.local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): Cython>=0.10 in /home/wanghm/.local/lib/python2.7/site-packages (from runcython)`
`Cleaning up...`

This might be caused by a silly mistake but I cannot figure out what the reason is.
Anyone who can help is most appreciated!
Thanks!

P.S. I'm compiling appolocaffe on a server where I don't have root access

**Comment by sherylwang** [comment]
conda remove libtiff also works for me

**Comment by Lakung** [comment]
conda remove libtiff works for me , thx~

**Comment by PencilAndBike** [comment]
conda remove libtiff also works for me. it should be anaconda path(where i set in PATH) conflicts with libtiff. thx

**Comment by juiceboxjoe** [comment]
conda remove libtiff worked

**Comment by luckybird1994** [comment]
conda remove libtiff

it works on me too! thx!

**Comment by lixiang-ucas** [comment]
conda remove libtiff

it works on me too! thx!
