### ISSUE TITLE
How to use Python layers?

### ISSUE THREAD

**Issue by XiaozhiChen** [Russell91/apollocaffe#14]
This is an amazing project!
I want to implement [Fast R-CNN](https://github.com/rbgirshick/fast-rcnn.git) using apollocaffe.  But I'm not sure how to use this [RoIDataLayer](https://github.com/rbgirshick/fast-rcnn/blob/master/lib/roi_data_layer/layer.py) in apollocaffe. This layer uses the Caffe python layer interfaces. It uses the following prototxt to declare a layer.
```
layer {
  name: 'data'
  type: 'Python'
  top: 'data'
  top: 'rois'
  top: 'labels'
  top: 'bbox_targets'
  top: 'bbox_loss_weights'
  python_param {
    module: 'roi_data_layer.layer'
    layer: 'RoIDataLayer'
    param_str: "'num_classes': 21"
  }
}
```

But It seems apollocaffe defines its own Pylayer instead of the official Caffe python layer interfaces. Should I change it to use Pylayer interfaces? Or is there a better way to use it directly?

Thanks very much!

**Comment by Russell91** [comment]
Apollocaffe is 100% backwards compatible with Caffe, so of course you can use Caffe PythonLayers! I would further encourage you to do so, over the PyLayer.

If you're interested though...
The motivation for the additional PyLayers is not particularly clear in any of the public facing code/documentation, but we find them quite nice internally. Unlike the Caffe PythonLayers, they support gpu operations, can be defined as a python class with no magic, and can take separate python arguments - thus avoiding the need to recompile the entire project when you make any small protobuf change to a layer. However, in the interest of keeping the message of ApolloCaffe smaller, we don't really market their capabilities. Perhaps this will change based on the new TheanoGPU layer, which lets you run theano kernels on your Caffe GPU data by just describing the kernels with a single string, which is the first publicly released PyLayer. But that could always be backported to a PythonLayer as well if it picks up any steam.

**Comment by XiaozhiChen** [comment]
Yeah I noticed the TheanoGPU layer. It's great! I will use PythonLayers for the time being. Thanks for your suggestion!

**Comment by XiaozhiChen** [comment]
Sorry but I still have some questions:
- Can I use ``net.f()`` to call a PythonLayer? How should I specify the following python parameters in ``net.f()``?
```
python_param {
    module: 'roi_data_layer.layer'
    layer: 'RoIDataLayer'
    param_str: "'num_classes': 21"
  }
```
- Is it possible to call a function which is defined in a PythonLayer through ``ApolloNet``?
- How to manipulate weights through ``ApolloNet``?

It would be great if you could show me examples how to do that. Thanks a lot!

**Comment by Russell91** [comment]
Perhaps you haven't read apollocaffe.com? We show how to call 
    net.f(''' python_param {
    module: 'roi_data_layer.layer'
    layer: 'RoIDataLayer'
    param_str: "'num_classes': 21"
    }''')

You can access the params through the net.params dictionary. To figure out what you're looking for, you can write:

    print net.params.keys()

**Comment by KelvinChan90** [comment]
Got it! Thanks.

**Comment by XiaozhiChen** [comment]
Got it! Thanks.

**Comment by atique81** [comment]
Hi @Russell91 

although you mentioned above that Apollocaffe is 100% backward compatible with Caffe, but I am unable to find a method similar to net.forward() (where net is a Caffe.Net object) that evaluates the whole network at once.

Am I missing something?
