### ISSUE TITLE
Import fails with CPU only apollocaffe

### ISSUE THREAD

**Issue by saurav111** [Russell91/apollocaffe#15]
The following error happens on trying to import apollocaffe:
ImportError: /home/saurav/apollocaffe-master/python/apollocaffe/cpp/_apollocaffe.so: undefined symbol: _ZN5caffe5Caffe10singleton_E
What could be the issue?
Edit: nm _apollocaffe.so | grep _ZN5caffe5Caffe10singleton_E shows that the symbol exists. Strange.
Also, looks like the symbol in question is caffe::Caffe::singleton_ which is not defined in libcaffe.so

**Comment by Russell91** [comment]
Con you verify that the old libcaffe.so is not being loaded on your ld_library_path? Runtime errors indicate this type of issue.

**Comment by saurav111** [comment]
Whoopsie, forgot to change LD_LIBRARY_PATH. Thanks a lot!
P.S. Awesome work with apollocaffe :)
