### ISSUE TITLE
NumpyDataLayer is sloooooow

### ISSUE THREAD

**Issue by jacobandreas** [Russell91/apollocaffe#19]
As would be expected given that we're serializing an object, deserializing it, and then copying it. Numpy is C-friendly, and it should be possible to point Caffe at the underlying memory location directly (this is how the native MemoryLayer works).

I have a grotesque Apollo version of MemoryLayer that does no serialization or copying. On an input of size (64, 512, 20, 20), it is approximately 70x faster than the NumpyData layer.

I'm happy to write an acceptable implementation, but would appreciate any initial thoughts you have on how to do this in a way most consistent with the existing framework.

**Comment by Russell91** [comment]
The NumpyData layer is already fairly optimized, and uses no python for the O(data size) parts. It already has a 20-50x speedup over the pure python version. Serialization using the cpp protobuf library adds some overhead - my timing shows 0.14 s for the 52MB data chunk you have - which is really not too bad all things considered.

You're welcome to do some profiling and see if you can speed up any bottlenecks in the current cython implementation. But there really is a simpler solution - after the first pass through the net when the blob is initialized, just use net.blobs['your_blob'].data[:] = your_numpy_array. The syntax is a little less convenient, but it should get the job done.

**Comment by Russell91** [comment]
Also, here is the profiling code I used if you got different results:

    import numpy as np

    from apollocaffe.layers import NumpyData
    import apollocaffe
    net = apollocaffe.ApolloNet()

    data = np.zeros((64, 512, 20, 20))
    for i in range(10):
        net.clear_forward()
        import time; s = time.time()
        net.f(NumpyData('a', data))
        print time.time() - s
        import time; s = time.time()
        net.blobs['a'].data[:] = data
        print time.time() - s

**Comment by jacobandreas** [comment]
Representative CPU thing:

0.262676000595 (net.f)
0.00521898269653 (net.blobs =)
0.00639295578003 (my thing)

Representative GPU:

0.405227899551
0.0072169303894
0.000205993652344

So there are gains for loading huge data chunks, but I agree that it's
probably not worth the effort over assigning directly to the blob in
practice. Thanks!
