### ISSUE TITLE
TheanoGPU Layer with parameters

### ISSUE THREAD

**Issue by xunhuang1995** [Russell91/apollocaffe#20]
Is there a way to use TheanoGPU Layer with its own parameters that can be updated?

**Comment by Russell91** [comment]
The easiest way would be to take the parameters of the layer as a separate input to be updated. For example, you could use an Embed layer (on Dev) which always get's the key 0 as input from a NumpyData layer. The Embed layer would then output the parameter matrix, which the TheanoGPU layer would take in as an input. This is what I've been doing at least.

Does that make sense?

**Comment by xunhuang1995** [comment]
Thank you. It makes sense!

Another question is, currently the output must be defined as a single expression of inputs. What if the input-output relation is so complicated that I need to use functions, theano.scan, e.t.c.?

**Comment by Russell91** [comment]
Well, the string is evaluated using eval(), and theano.scan will be in the namespace, so it is possible you can make it work. The alternative is to look at the implementation of TheanoGPU in apollocaffe.layers.python_layers and create a copy of that class with some of the extra features you would like.

**Comment by xunhuang1995** [comment]
I will try that. Thanks a lot!
