### ISSUE TITLE
pre-trained vectors

### ISSUE THREAD

**Issue by deeplearningmachine** [Russell91/apollocaffe#23]
I just wonder if you have an example of loading pre-trained vectors such as those generated with Word2Vec?

**Comment by Russell91** [comment]
Please see e.g. https://github.com/Russell91/apollocaffe/issues/24. If you have a numpy array of the desired parameters, you can load in the parameters with 

    net.params['param_name'].data[:] = your_array

before training. You can also access the params by net.layers['layer_name'].blobs[param_index].data[:] if that is more convenient.

**Comment by deeplearningmachine** [comment]
Thanks a lot, Russell!
