### ISSUE TITLE
Is there a way to modify blob data using python API?

### ISSUE THREAD

**Issue by Grindary** [Russell91/apollocaffe#24]
I encountered this issue when trying to load pretrained proto data into parameter blobs. As my layers names are different from those in the proto, I cannot use net.load() directly. Instead I have to manually read data from proto and write them into blobs.

Howevere I get error that blob data of apollocaffe is not writable:

   "attribute 'data' of 'apollocaffe.cpp._apollocaffe.Blob' objects is not writable"

Is there a way to implement blob writing through python API, or do I have to write in C++ instead?

Thanks a lot for your response!

**Comment by Russell91** [comment]
Absolutely! Standard caffe will give you the same error, which comes from
Numpy. The trick is to say e.g.

    net.blobs['myblob'].data[:] = np.zeros((2,3,4,5))

Note the use of `[:]`

**Comment by Grindary** [comment]
WOW that's super cool!!

Again thanks for this super quick response! It really helped a lot : )
