### ISSUE TITLE
lstm change batch size

### ISSUE THREAD

**Issue by yuzhile** [Russell91/apollocaffe#25]
when I use lstm unit,I have different batches for every forward.I find that lstm allow fixed size batch only.I view the lstm codes,I find:
void LstmUnitLayer<Dtype>::LayerSetUp(const vector<Blob<Dtype>*>& bottom,
      const vector<Blob<Dtype>*>& top) {
...
  channels_ = lstm_unit_param.num_cells();
  input_data_size_ = bottom[0]->shape(1);
  num_ = bottom[0]->shape(0);
  M_ = num_;
  N_ = channels_;
  K_ = input_data_size_;
...
}
num_ is initialized in setup function.so the batch size is fixed when lstm unit is initialized.how I change it?

**Comment by Russell91** [comment]
Hmm, I'd be curious about your application that is changing batch sizes. Nevertheless, I don't think this should be a problem. Make sure you don't have any other state dependent on num_ and then simply overwrite both num_ and M_ in the Reshape function, which is called on every forward pass.

**Comment by yuzhile** [comment]
oh,I understand it.thank you very much
