### ISSUE TITLE
LSTM reshape issue

### ISSUE THREAD

**Issue by Grindary** [Russell91/apollocaffe#28]
Hi,
I noticed that during the reshape process of lstm unit, the value of batch size (num_) stay unchanged. However what I have is a varying batch size. 
Therefore I simply added a line in reshape function of lstm to make num_ equal to current batch size:
num_ = bottom[0]->shape(0);
and the buffer and output sizes are changed subsequently

It worked fine so far but i still want to make sure that this change won't bring any terrible effects, or will it?

**Comment by Russell91** [comment]
Yes, your pull request looks good. If you can remove the commented out lines and verify that `make lint` does not fail, I could accept the pull request on dev.

**Comment by yuzhile** [comment]
Hi,I remove the comment out lines and run command that make lint and verify no lint errors:
    root@yuzhile-Z97X-Gaming-7:~/work/cpp/caffe/apollocaffe-master# make clean
    root@yuzhile-Z97X-Gaming-7:~/work/cpp/caffe/apollocaffe-master# make lint
    No lint errors!

**Comment by Grindary** [comment]
Thanks a lot for accepting this pull request! 
And thank you @yuzhile for doing the verification.
