### ISSUE TITLE
hungarian algorithm 

### ISSUE THREAD

**Issue by chenfsjz** [Russell91/apollocaffe#32]
@Russell91 
 I think the maxmatch problem is very interesting, I have  read the hungarian algorithem.You know the coordinates of a box in the groundtruth are bound to maximum dimition of the box.
 1. why you divide the value of "pred_value - label_value" by 2000 when  compute the match_cost matrix. 
 2.  And in the following steps, you add the each element of match_cost with 100, it's just like a kind of  normalization method.
     

        for (int i = 0; i < num_pred; ++i) {
          for (int j = 0; j < num_pred; ++j) {
        const int idx = i * num_pred + j;
        match_cost.push_back(0.);
        loss_mat.push_back(0.);
        if (j >= num_gt_[n]) { continue; }
        for (int c = 0; c < channels; ++c) {     // 4 coordinates
          const Dtype pred_value = box_pred_data[offset + c * height + i];
          const Dtype label_value = boxes_data[offset + c * height + j];    
          match_cost[idx] += fabs(pred_value - label_value) / 2000.;
          loss_mat[idx] += fabs(pred_value - label_value);
        }
        CHECK_LT(match_cost[idx], 0.9);
        match_cost[idx] += i;
        const int c_x = 0;
        const int c_y = 1;
        const int c_w = 2;
        const int c_h = 3;

        const Dtype pred_x = box_pred_data[offset + c_x * num_pred + i];
        const Dtype pred_y = box_pred_data[offset + c_y * num_pred + i];

        const Dtype label_x = boxes_data[offset + c_x * num_pred + j];
        const Dtype label_y = boxes_data[offset + c_y * num_pred + j];
        const Dtype label_w = boxes_data[offset + c_w * num_pred + j];
        const Dtype label_h = boxes_data[offset + c_h * num_pred + j];

        float ratio;
        if (this->phase_ == TRAIN) {
          ratio = match_ratio_;
        } else {
          ratio = 1.0;
        }

        if (fabs(pred_x - label_x) / label_w > ratio ||
            fabs(pred_y - label_y) / label_h > ratio) {
          match_cost[idx] += 100;
          }
          }
         }
   I just wander how to decide the  these impact factors in the hungarian problem. Now I want to used the hungarian algorithem to compute the maxmatch of two binary matrix which consists of 0 or 1.Does it's depend on your experience or  regular rule.

**Comment by Russell91** [comment]
The code you see implements 3 tiers of matching costs. The system is described in the paper if you're interested. Please give the matching section a read and let me know if you still have any questions. But the Hungarian library you're looking at is straightforward and can indeed be used to compute simple 0-1 matchings as well.
