### ISSUE TITLE
Using Deconvolutional layer in Python

### ISSUE THREAD

**Issue by xinggangw** [Russell91/apollocaffe#33]
Hi Russell,

I am trying to use the "deconvolution" layer in Python interface.

In "caffe_layers.py", I add the following lines:

```python
 41 class Deconvolution(Layer):
 42     def __init__(self, name, kernel_dim, num_output, weight_filler=None, bias_filler=None, **kwargs):
 43         kwargs['kernel_h'] = kernel_dim[0]
 44         kwargs['kernel_w'] = kernel_dim[1]
 45         kwargs['num_output'] = num_output
 46         super(Deconvolution, self).__init__(self, name, kwargs)
 47         if weight_filler is None:
 48             weight_filler = Filler('xavier')
 49         self.p.convolution_param.weight_filler.CopyFrom(weight_filler.filler_param)
 50         if bias_filler is None:
 51             bias_filler = Filler('constant', 0.)
 52         self.p.convolution_param.bias_filler.CopyFrom(bias_filler.filler_param)
```

When invoking the defined Deconvolution layer, I got the following error:

File "./apollocaffe/python/apollocaffe/layers/layer_headers.py", line 57, in parse
    raise AttributeError('Layer %s has no keyword argument %s=%s' % (param_type, k, v))
***AttributeError: Layer Deconvolution has no keyword argument kernel_w=32***

Could you help to tell me what I ignored? I tried to add some definitions about deconvolution layer in "caffe.proto". But it doesn't work. 

Thanks a lot!

**Comment by Russell91** [comment]
Ah yea, this is a little tricky. If you look at the prototxt for a
deconvolution layer, you'll notice it actually uses a convolution
parameter. In this case, your best bet is to make the deconvolution layer a
wrapper (perhaps a subclass even)  around the convolution layer__init__
function, which changes the contents of self.p.name to 'Deconvolution'
before returning. Please submit a pull request if you get it working!

**Comment by xinggangw** [comment]
Thanks for the helpful suggestions. It works now. Pull request #34 submitted.

I am working on semantic segmentation using Apollocaffe. Later when I finished the experiments, I can submit some example codes.
