### ISSUE TITLE
Gradient inference of lstm_unit_layer differ in GPU and CPU version.

### ISSUE THREAD

**Issue by GoYchen** [Russell91/apollocaffe#36]
Dear Russell,
Thank you very much for your great works and I am trying to use this code in my project. 
But I found that the forward and backward functions in lstm_unit_layer.cpp and lstm_unit_layer.cu are not the same. I can understand the CPU version forward and backward functions, but I can't understand the GPU version. Could you give me some information to help me understand these two versions of gradient inference?

Thank you for your time.

**Comment by Russell91** [comment]
Yeah, this was discovered recently and fixed in dev. See https://github.com/Russell91/apollocaffe/pull/38.  I'll go ahead and bring these changes over.
