### ISSUE TITLE
How can I fork this repo to my account when I've already forked caffe?

### ISSUE THREAD

**Issue by CharlesShang** [Russell91/apollocaffe#39]
Allow me to ask this stupid question :-(
When I click the fork button, the page goes to my caffe repo :-< and fails to fork apollocaffe.

**Comment by Russell91** [comment]
Well, it is a fork of caffe, so I don't think github will let you do that. The easiest way would be to clone the repo, add a new apollocaffe repo on github. Type `git remote add charles https://github.com/charlesshang/apollocaffe && git push charles master`. Best of luck!
