### ISSUE TITLE
Cannot find the tutorial website anymore

### ISSUE THREAD

**Issue by mgarbade** [Russell91/apollocaffe#5]
Hey 
Unfortunately I cannot find the original project website anymore. I guess the address was "apollo.deepmatter.io". It had a nice example of using recurrent layers and lstm layers.

Did you switch off that website for any reason?

**Comment by jacobandreas** [comment]
http://www.wakerapp.com/?

**Comment by Russell91** [comment]
Oh no, how did you find that? The Caffe developers made some complaints about the apollo website/docs not giving them enough credit, so I took it down when migrating to the apollocaffe fork to appease them. I'll try to put up a stripped down version that only has the basics soon.

**Comment by jacobandreas** [comment]
Oh, sorry---was sent it by a friend at Berkeley.

FWIW I sit right next to the caffe devs and like your python wrapper a lot
better. Thanks for putting this together!

Is it OK to file issues right now, or should I wait until the branding
reaches a state everyone is happy with?

**Comment by Russell91** [comment]
Yea, filing issues with any bugs or feature requests is appreciated as it improves the quality of apollocaffe. You've also reminded me that I just need to go ahead and write these new docs.

**Comment by Russell91** [comment]
The tutorial website is now available at apollocaffe.com.

**Comment by mgarbade** [comment]
Thanks for your reply. In the previous version of your website you had an example called "summation.py" which explained a network including an "LSTM"-layer that learns to add up a sequence of numbers. Could you upload the explanation to this example again?
I'm trying to get acquainted with the concept of LSTM and doing this in caffe would really help me.

**Comment by Russell91** [comment]
Sure, just added this. Please check out the LSTM tutorial linked under http://apollocaffe.com/#Tutorial

**Comment by futurely** [comment]
@Russell91 , you should consider switching to DMLC/MXNet of which is [much more open and domestic](https://github.com/dmlc/mxnet/blob/master/CONTRIBUTORS.md). The project initiators are from multiple universities that have created diverse deep learning libraries such as cxxnet, minerva and purine2. They probably will not try to dominate the development of the project and ignore important contributions from competing universities.
