### ISSUE TITLE
Cannot import apollocaffe in PySpark

### ISSUE THREAD

**Issue by ashraaghav** [Russell91/apollocaffe#52]
I am trying to use apollocaffe with PySpark. I installed everything following the installation instructions in the site: http://apollocaffe.com/#Installation 
I have added the environment variables LD_LIBRARY_PATH and PYTHONPATH in .bashrc. I am able to import apollocaffe in Python and PySpark also but only in the driver. For my worker, which is the same machine and same user, it is giving the following error:

ImportError: ('No module named apollocaffe', <function subimport at 0x7f96dbe12b90>, ('detector',))

What can I do to make it to work?

**Comment by Russell91** [comment]
you should be able to find an apollocaffe.so file, which is a cython compiled module that python can import. Please make sure you can cd to the directory containing apollocaffe.so and run python -c 'import apollocaffe'. If that works, you will be able to debug your own machine settings.

**Comment by ashraaghav** [comment]
I copied the package into /usr/lib/python2.7/dist-packages and I also had to copy libcaffe.so to /usr/lib. Now it is working. I am guessing it was because PySpark worker was not able to read the package from the current location because it was installed in user home folder.
