### ISSUE TITLE
why the old apollo were gone

### ISSUE THREAD

**Issue by icycandy** [Russell91/apollocaffe#6]

**Comment by nicodjimenez** [comment]
The core devs decided that the best choice for the project was for it to be integrated more closely with the caffe project as a fork, which was most conveniently done as a separate repo.  We have made substantial improvements over the old apollo (more intuitive syntax using prototxt strings, c++ support, ...) which will be described in an upcoming article.  In the meantime, the old examples should work with the new apollo with minor modifications.  See examples/apollocaffe/ which show the minor changes in syntax.

**Comment by icycandy** [comment]
Many thanks.
