### ISSUE TITLE
Copy and Paste bug in "caffe_layers.py"

### ISSUE THREAD

**Issue by pcmoritz** [Russell91/apollocaffe#7]
Dear all,

apollocaffe is great work, congrats!

Just a quick note: In the InnerProduct Layer, you are assigning to convolution_param instead of inner_product_param.

-- Philipp.

**Comment by Russell91** [comment]
Hey Phillip,

Thanks for the bug report. We had fixed this on dev, but hadn't merged it into master yet. It was a good reminder to go ahead and bring over those changes though, so it should be working now

Best,
Russell

**Comment by pcmoritz** [comment]
Thanks a lot!
