### ISSUE TITLE
InnerProduct above dynamically-resized Convolution fails silently

### ISSUE THREAD

**Issue by jacobandreas** [Russell91/apollocaffe#9]
```python
#!/usr/bin/env python2

from apollocaffe import ApolloNet, layers
import numpy as np

net = ApolloNet()

net.clear_forward()
net.f(layers.NumpyData("input", data=np.zeros((1, 8, 4, 4))))
net.f(layers.Convolution("conv1", (1,1), 1, bottoms=["input"]))
net.f(layers.InnerProduct("output", 8, bottoms=["conv1"]))
net.backward()

net.clear_forward()
net.f(layers.NumpyData("input", data=np.zeros((1, 16, 4, 4))))
net.f(layers.Convolution("conv2", (1,1), 1, bottoms=["input"]))
net.f(layers.InnerProduct("output", 8, bottoms=["conv2"]))
net.backward()
```

Here we have

- a dynamically-resizing input layer
- a convolution above it
- an inner product layer

On the first pass, the weight matrix for the inner product layer is set according to the size of the first input. It is the wrong size to process the second input, but the library doesn't complain.

**Comment by jacobandreas** [comment]
(Removing the convolutional layer and connecting the inner product directly to the input generates an appropriate error.)

**Comment by Russell91** [comment]
So this scared me for a second, but I think everything is working as intended. When I run the following:

    #!/usr/bin/env python2

    from apollocaffe import ApolloNet, layers
    import numpy as np

    net = ApolloNet()

    net.clear_forward()
    net.f(layers.NumpyData("input", data=np.zeros((1, 8, 4, 4))))
    net.f(layers.Convolution("conv1", (1,1), 1, bottoms=["input"]))
    print net.blobs["conv1"].shape
    net.f(layers.InnerProduct("output", 8, bottoms=["conv1"]))
    net.backward()

    net.clear_forward()
    net.f(layers.NumpyData("input", data=np.zeros((1, 16, 4, 4))))
    net.f(layers.Convolution("conv2", (1,1), 1, bottoms=["input"]))
    print net.blobs["conv2"].shape
    net.f(layers.InnerProduct("output", 8, bottoms=["conv2"]))
    net.backward()

I get:

[1, 1, 4, 4]
[1, 1, 4, 4]


So the InnerProduct is seeing data of exactly the same shape. ApolloCaffe notices that the bottoms of the InnerProduct have changed and moves around the pointers so that the InnerProduct will process the "conv2" input, and life is good.

**Comment by jacobandreas** [comment]
Ah, sorry, sloppiness on my part---those (4, 4)s should be different in the two cases. But when I change them here the script crashes appropriately, so the problem is somewhere else in my code. Sorry about this.

**Comment by Russell91** [comment]
No problem
